// todo-list/src/03-dynamic/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  text = '';

  tasks = [
    { id: 1, text: 'Learn Angular', completed: true },
    { id: 2, text: 'Look for a job', completed: false },
    { id: 3, text: 'Forget everything' },
  ];

  handleSubmit(event: SubmitEvent) {
    event.preventDefault();

    const maxId = this.tasks.length ? this.tasks[this.tasks.length - 1].id : 0;
    this.tasks.push({ id: maxId + 1, text: this.text });
    this.text = '';
  }

  handleSpanClick(index: number) {
    this.tasks[index].completed = !this.tasks[index].completed;
  }

  handleButtonClick(index: number) {
    this.tasks.splice(index, 1);
  }
}

<form (submit)="handleSubmit($event)">
  <input placeholder="What next?" autofocus name="text" [(ngModel)]="text" />
  <button>Add</button>
</form>
<ul>
  <li *ngFor="let task of tasks; index as i">
    <span
      [class]="{ completed: task.completed }"
      (click)="handleSpanClick(i)"
      >{{ task.text }}</span
    >
    &nbsp;
    <button (click)="handleButtonClick(i)">x</button>
  </li>
</ul>

// react-todo-list/src/app/app.js
import { useState } from "react";
import List from "./list/list";
import Form from "./form/form";

const DEFAULT_TASKS = [
  { id: 1, text: "Learn React", completed: true },
  { id: 2, text: "Look for a job", completed: false },
  { id: 3, text: "Forget everything" },
];

function App({ name }) {
  const [tasks, setTasks] = useState(DEFAULT_TASKS);

  // return React.createElement("form", {
  //   children: [
  //     React.createElement("input", {
  //       placeholder: "What next?",
  //       autoFocus: true,
  //     }),
  //     React.createElement("button", { children: "Add" }),
  //   ],
  // });

  const handleSubmit = (text) => {
    setTasks((tasks) => {
      const maxId = tasks.length ? tasks[tasks.length - 1].id : 0;
      return [...tasks, { id: maxId + 1, text }];
    });
  };

  const handleSpanClick = (id) => {
    setTasks((tasks) =>
      tasks.map((task) =>
        task.id === id ? { ...task, completed: !task.completed } : task
      )
    );
  };

  const handleButtonClick = (id) => {
    setTasks((tasks) => tasks.filter((task) => task.id !== id));
  };

  return (
    <>
      <h1>{name}'s Todo List</h1>
      <Form onSubmit={handleSubmit} />
      <List
        tasks={tasks}
        onSpanClick={handleSpanClick}
        onButtonClick={handleButtonClick}
      />
    </>
  );
}

export default App;
